# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Christian Philip
description: >-
  I asked ChatGPT to write something here, and this is what it said.
  Hi, I’m Christian, a dedicated soccer player with big dreams of playing
  at the collegiate level. I’ve been passionate about the game for as long
  as I can remember, and I work hard both on and off the field to grow as
  an athlete and a teammate. Whether it’s perfecting my skills, breaking
  down game strategies, or pushing myself in training, I’m always striving
  to improve. Alongside soccer, I value academics and am committed to
  balancing my studies with my athletic goals. Here, I’ll share highlights,
  training sessions, and moments from my journey as I work toward earning a
  spot on a college team.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: minima
remote_theme: "mmistakes/so-simple-theme@3.2.0"

plugins:
  - jekyll-feed

lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
